---
apiVersion: apps/v1
kind: Deployment                 
metadata:
  name: go-redis-app            
spec:
  replicas: 2                  
  selector:
    matchLabels:
      app: go-redis-app       
  template:                  
    metadata:
      labels:               
        app: go-redis-app 
    spec:
      containers:
      - name: go-redis-app
        image: priyankasaggu119/go-redis-task:1.0.0 
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - containerPort: 8080 
#         livenessProbe:         
#           httpGet:
#             path: /health
#             port: 8080
#             scheme: HTTP
#           initialDelaySeconds: 5
#           periodSeconds: 15
#           timeoutSeconds: 5
#         readinessProbe:       
#           httpGet:
#             path: /readiness
#             port: 8080
#             scheme: HTTP
#           initialDelaySeconds: 5
#           timeoutSeconds: 1                
        env:                   
          - name: DEMO_APP_ADDR
            value: 0.0.0.0:8080
          - name: DEMO_REDIS_ADDR
            value: redis-master:6379
          - name: REDIS_HOST
            value: redis-master
          - name: REDIS_PORT
            value: "6379"    
---
apiVersion: v1
kind: Service                 
metadata:
  name: go-redis-app-service 
spec:
  type: NodePort            
  ports:                   
  - name: http
    port: 9090
    targetPort: 8080
  selector:
    app: go-redis-app     
